### ISSUE TITLE
set number of active requests

### ISSUE THREAD

**Issue by balazserdos** [website-scraper/node-website-scraper#219]
is there any option to set the number of active requests? The site is crashed cause of the huge amount of requests at the same time. options like this would be nice in the future
**interval** - between 2 requests
**maxConcurrency** - how many requests are in progress

Thank you
#129

**Comment by s0ph1e** [comment]
Hi @balazserdos 
There is no such option now

Thanks for suggestion, I'll consider adding it in future

**Comment by mtr980** [comment]
how to bypass login or download content after login? Thanks

**Comment by aivus** [comment]
Hi @mtr980. Your question is not related to the subject of this ticket. 
Please try to use search by issues or create separate issue for you question.

BTW, see https://github.com/s0ph1e/node-website-scraper#request

**Comment by s0ph1e** [comment]
[requestConcurrency](https://github.com/website-scraper/node-website-scraper#requestconcurrency) option was released in version 3.3.0

**Comment by erickhavel** [comment]
For anyone looking for a bit more flexibility, here's a plugin with randomized min/max timeouts between requests:

https://benjaminhorn.io/code/request-throttle-for-npm-package-website-scraper/

**Comment by s0ph1e** [comment]
Hi @erickhavel 

Great article 👍 
Thank you, I'll add link to your solution to readme so others can find it there
