### ISSUE TITLE
"subdirectories" Configuration not working well

### ISSUE THREAD

**Issue by vladejs** [website-scraper/node-website-scraper#238]
Hi, I'm using the library to scrape a site and I need all the assets on their root folders:
```
css/[all CSS here]
js/[all JS here]
```
Turns out that it works, but in some cases it creates subdirectories with the very same structure. I want the scrapper to put all configured assets (no matter the deep page it belongs to) to be on the root folder.

![outroot](https://user-images.githubusercontent.com/12637186/30657067-485de886-9e04-11e7-8f9c-36e95f2837ac.png)

Currently, it's taking the assets and relatively creating the corresponding folder:
```
/about/members/css/[allCSS of the members subfolder]
```

I'm using version 3.3.0

**Comment by s0ph1e** [comment]
Hi @vladejs 
Could you please provide options which you are using? 
It would be easier for me to find a problem

**Comment by vladejs** [comment]
This is the config I'm using @s0ph1e :
```
subdirectories: [
                { directory: 'img', extensions: ['.jpg', '.png', '.svg', '.gif', '.jpeg', '.bmp'] },
                { directory: 'js', extensions: ['.js'] },
                { directory: 'css', extensions: ['.css'] },
                { directory: 'fonts', extensions: ['.eot', '.woff', '.woff2'] }
            ],
```

**Comment by s0ph1e** [comment]
I need all `options` object in order to reproduce issue (at least `urls`, `filenameGenerator`, `sources`, `recursive`, `urlFilter`) because this functionality is covered with tests and was used a lot of times with no problems. Probably your issue is some edge case.

BTW `subdirectories` works only with default *byType* filenameGenerator. If you are using *bySiteStructure* filenameGenerator - it has no effect.

**Comment by vladejs** [comment]
Thanks for clarifying. I kind of have an edge case, because if I scrape a site with subfolders on it, with this options, it correctly put the assets on their corresponding folder, but **into the subfolder their belongs**:
```
/teams/members/
 - css/members.css
 - css/page.css 
```
Currently, there isn't a feature that specifies whether the assets should remain on the root folder, in order to allow this result:
```
- css 
  - teams_member_style.css
  - teams_member_page.css
- js
- images
- teams
  - members
     - index.html
     - [look ma', no other assets here]
```

Nonetheless, this is my configuration:
```
const options = {
            urls: ['mywebsite.com'],
            directory: outputFolder,
            recursive: true,
            maxRecursiveDepth: 20,
            maxDepth: 20,
            prettifyUrls: true,
            updateMissingSources: true,
            subdirectories: [
                { directory: 'img', extensions: ['.jpg', '.png', '.svg', '.gif', '.jpeg', '.bmp'] },
                { directory: 'js', extensions: ['.js'] },
                { directory: 'css', extensions: ['.css'] },
                { directory: 'fonts', extensions: ['.eot', '.woff', '.woff2'] }
            ]
        }
```
Thanks

**Comment by vladejs** [comment]
I tested out a config where I put a slash on the directories. This way the assets are all saved on the root but I'm getting assets overwriting each other:
```
subdirectories: [
                { directory: '/img', extensions: ['.jpg', '.png', '.svg', '.gif', '.jpeg', '.bmp'] },
                { directory: '/js', extensions: ['.js'] },
                { directory: '/css', extensions: ['.css'] },
                { directory: '/fonts', extensions: ['.eot', '.woff', '.woff2'] }
            ]
```
With that config I'm also getting references like this one:
```
../../../../../css/index.css
```

In my case, that resolves well the root CSS folder, but I identified cases when the saved file isn't the one that belongs to the html it's referenced from (overwriting issue?)

**Comment by vladejs** [comment]
@s0ph1e , I think that the problem isn't what I'm mentioning here, but instead a subdirectory crawling issue. I posted it in #239
