### ISSUE TITLE
Issues with current scraping strategies

### ISSUE THREAD

**Issue by vladejs** [website-scraper/node-website-scraper#246]
Hello @s0ph1e , #239 solution worked excellently. Thank you.

This one is related to the current strategies. I'm using the default because I want my links to be exact like the original ones, no matter what the extension, so, for example, if a link is `/folder/about.php` it works correctly, but if the link do not ends with an extension (`www.site.com/folder/teams`) I end up with a `/folder/teams.html` file, and I want `folder/teams/index.html` file.

You may answer: "Use the `bySiteStructure` strategy". 

**I can't**, because I will end up with subfolders for all links, including `php` ones. So, from the previous example, the PHP link will be converted as: `/folder/about.php/index.html` which is not the intention.

I think that what I'm trying to achieve is a hybrid between both strategies.

Can we include an extra option for the default strategy called something like `"respectRootLinks": true` in which, when found a link without extension, it creates a folder for it?

```
- http://www.site.com/about/       --> www.site.com/about/index.html
- http://www.site.com/about        --> www.site.com/about/index.html
- http://www.site.com/about.php  --> www.site.com/about.php
```

PD: You can test with the same URL I sent you before.

**Comment by s0ph1e** [comment]
Hey @vladejs 

Filename generators `byType` and `bySiteStructure` are built-it strategies but you can use any custom function as `filenameGenerator`, for example:
```javascript
const crypto = require('crypto');

scrape({
  urls: ['http://example.com'],
  directory: 'tmp/' + new Date().getTime(),
  filenameGenerator: (resource, options, occupiedFileNames) => { // random filename
	return crypto.randomBytes(20).toString('hex')
  }
})
```

So I suggest to create your own strategy mixing [byType generator code](https://github.com/website-scraper/node-website-scraper/blob/aa18aab99b21e22012a03ee2c25b6477fba878b5/lib/filename-generator/by-type.js) with [bySiteStructure generator code](https://github.com/website-scraper/node-website-scraper/blob/aa18aab99b21e22012a03ee2c25b6477fba878b5/lib/filename-generator/by-site-structure.js)

**Comment by vladejs** [comment]
Thanks @s0ph1e , I forked the library and find out that by modifying 2 files I get what I want (at 95%).

```
// lib/config/resource-ext-by-type.js, line 5
defaultExtensions[types.html] = [ '.html', '.htm', '.php' ];
```
That way, using the bySiteStructure strategy I get correct php files instead of `about.php/index.html` folders.

I'll try creating my own method though I'm not sure how to tell: "For this kind of file use the default, for this other one use bySiteStructure"

**Comment by vladejs** [comment]
Hi @s0ph1e , several days after trying and trying, I haven't figured out how to achieve this at a 100% rate. 

Maybe I don't understand well how to implement the "Exact file URL" strategy. I wonder if you could help me do it and merge into the built in strategies. That would improve the library significantly, because that behavior is the default people expect when crawling a site.

I have other questions but not related to strategies, so I'll open another issue

Thanks in advance

**Comment by s0ph1e** [comment]
I'm not going to implement this, have no time. 
But if you feel you can do this - contributions are welcome (with tests and small description in readme)
