### ISSUE TITLE
Resources that gives 404 aren't processed

### ISSUE THREAD

**Issue by vladejs** [website-scraper/node-website-scraper#249]
* **website-scraper version:**
3.3.1

**Please provide your full options object:**

<details>
<summary>default options</summary>

```js
urls: [ any url that has missing resources ],
httpResponseHandler: (response) => /* reject the promise if response.statusCode is 404 */
```

</details>

**What is expected result?**
If a site contains a resource (like a favicon) which isn't available:
`<link rel="shortcut icon" href="media/favicon.ico"> // favicon.ico file doesn't exist`

I expect to end up with the same `link` tag pointing to the missing resource locally

**What is actual result?**
The link tag pointing to the resource, but as an absolute URL:
`<link rel="shortcut icon" href="http://www.site.com/media/favicon.ico">`

**Comment by s0ph1e** [comment]
Hi
Do you have `updateMissingSources` in options object?

**Comment by vladejs** [comment]
Yes, i do, and is set to `true`.

**Comment by vladejs** [comment]
I'll close this because disabling the option solve my concern 
need to read the documentation carefully next time :)
thanks
