### ISSUE TITLE
Remove Resources 

### ISSUE THREAD

**Issue by milabron** [website-scraper/node-website-scraper#250]
Hello,
It would be a good option to remove javascript or css, for example to delete script that starts with analytics, or to put a callback to edit the html before serving in the directory.

**Comment by s0ph1e** [comment]
Hi @milabron 
You can achieve this by customizing selectors (they support jquery-style) for sources, for example:
```javascript
// download all scripts except those which starts with '//some-analytics.com'
{
  sources: [  
    {selector: 'script:not([src^="//some-analytics.com"])', attr: 'src'}
  ]
}
```

or by using [httpResponseHandler](https://github.com/website-scraper/node-website-scraper#httpresponsehandler) option, for example:

```javascript
{
httpResponseHandler: (response) => {
       const url = response.request.href;
  	if (url.startsWith('http://some-analytics.com')) {
		return Promise.reject(new Error('Analytics script found'));
	} else {
		return Promise.resolve(response.body)
	}
  }
}
```

Hope this helps

**Comment by s0ph1e** [comment]
also you can use [urlFilter](https://github.com/website-scraper/node-website-scraper#urlfilter) option

**Comment by milabron** [comment]
Amazing sofia! Thank you for the quick response, but now my second incognita, if for example the analitycs code goes in line, there is some way to use regular expressions but in the html file before being delivered, actually my problem will also come in the analytics and facebook inline script.

**Comment by s0ph1e** [comment]
You can use  `httpResponseHandler` option for this as well:
```javascript
{
httpResponseHandler: (response) => {
       const htmlBody = response.headers['content-type'].startsWith('text/html') && response.body;
       const re = /YOUR_REGEXP_HERE/;
       if (htmlBody && re.test(htmlBody)) {
                const updatedHtmlBody = htmlBody.replace(re, ''); 
		return Promise.resolve(updatedHtmlBody);
	} else {
		return Promise.resolve(response.body)
	}
  }
}
```

You are welcome)

**Comment by chiqui3d** [comment]
Thanks beautifully, I close the issues and get to work.

**Comment by milabron** [comment]
Thanks beautifully, I close the issues and get to work.
