### ISSUE TITLE
hello,

### ISSUE THREAD

**Issue by caidahui** [website-scraper/node-website-scraper#257]
Can I make a friend? I come from China

**Comment by s0ph1e** [comment]
Hi @caidahui 
We can be collaborators on this project. Feel free to submit issues/bugs/ideas

**Comment by caidahui** [comment]
no no no Is to make friends with you

**Comment by s0ph1e** [comment]
Sorry but Github is a platform for building software, not for searching friends

**Comment by caidahui** [comment]
Well, it's the skills
