### ISSUE TITLE
Can't use scraper

### ISSUE THREAD

**Issue by alphonse-92** [website-scraper/node-website-scraper#258]
Hi...
I'm trying to use webiste-scraper for a personal test using [Gobuffalo](https://github.com/gobuffalo/buffalo), but I can't to get work, first I encountered some errors about "fs, net, tls" when compiling... Searching the web I found that I had to add the following lines to my webpack config:

```
node: {
    console: true,
    fs: 'empty',
    net: 'empty',
    tls: 'empty'
  }
```
Trying again and with no errors when compiling I add the basic usage on my Javascript, and I get this error on the chrome console:

``
Uncaught TypeError: Cannot read property 'prototype' of undefined
``

I hope you can help me.
Thanks.

**Comment by s0ph1e** [comment]
Hi @alphonse-92 
Do I understand correctly that you are trying to run it in browser? 

Module `website-scraper` is not supposed to run in browser, it is for server side and can be used with nodejs only.

**Comment by alphonse-92** [comment]
That's right @s0ph1e...
I wanted to run it in brower..... But... Well...
Thanks for the response
