### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by azypka** [website-scraper/node-website-scraper#259]
Is is possible to use proxy with this scrapper? If not, please consider implementing it.
Advanced strategies could use:
- rotate proxy every X request
- wait time between next request
- preserve cookie per proxy
There are pages that are using good protection from scrapping, implementing of above would make life easier.

**Comment by aivus** [comment]
Hi @azypka 

This module uses [request](https://www.npmjs.com/package/request) package for making requests.

It seems that `request` package supports proxies configuration.
See https://github.com/request/request#proxies

You can specify any custom options in `request` option of this module.
https://github.com/website-scraper/node-website-scraper/blob/501af90c995508fbfbd623f63d391b0ccf2744a8/README.md#request

**Comment by aivus** [comment]
According to your second part of question:
> Advanced strategies could use:

Proxy management is out of scope this module.
If it's required you can create some wrapper for this or forward your proposal to `request` package repository

I'm closing this issue now, but if you have any issue with using proxy with this package feel free to open new issue.

Thank you

**Comment by mzachariadis** [comment]
I'm trying to set proxy too, but I can't figure out how to do this. As I can see in the **request** node module, in order to set a proxy you have to use defaults method just like: 
```
let proxyUrl = `http://${proxy.host}:${proxy.port}`;
requestWrapper = request.defaults({'proxy':proxyUrl});
```

As I can see in the website-scraper request.js file you set the requestOptions like -> 
```
return get(requestOptions).then((response) => { ... }
```

Is there a way to pass proxy settings through requestOptions? If yes, is it possible to provide some code on how to do this? 

Thank you !

**Comment by mzachariadis** [comment]
I added proxy property inside requestOptions and it's fine as well. So ignore my previous message.
```
requestOptions.proxy = `http://${proxy.host}:${proxy.port}`;
```

**Comment by i-ce-fish** [comment]
It is  work


`
 scrape({
        urls: [encodeURI(demo.url)],
        directory: 'test/' + new Date().getTime(),
        request: {
            headers: {
                Cookie: demo.header.Cookie,
            },
            proxy: 'http://xxxxxx:port'
        },
})
`
