### ISSUE TITLE
Pass already fetched html code from request module

### ISSUE THREAD

**Issue by mzachariadis** [website-scraper/node-website-scraper#262]
Hello!! I use request module to fetch html code from websites. So I would like to feed **website-scraper** with the already have html code and avoid duplicate calls. Is it possible with the current version? 

Thanks !

**Comment by s0ph1e** [comment]
Hello @mzachariadis

If you want to use this module with existing html body (instead of passing url) - now that's not possible because **website-scraper** takes url as option and requests html body for it. There is no way to feed existing html body

Hope it helps

**Comment by s0ph1e** [comment]
@mzachariadis I believe it is possible. I'll consider this case in future updates
