### ISSUE TITLE
Different encodings for different file types

### ISSUE THREAD

**Issue by bengro** [website-scraper/node-website-scraper#264]
I'm using node-website-scraper to scrape a website with text and images. When I use the options
`request.encoding : 'binary'` I'm getting encoding issues for content pages; understandably as binary encoding is lossy for UTF8 content. When I change it to 'request.encoding: 'utf8'` the content is encoded properly, but images are not fetched as they are not stored as binary. 

Can you confirm that this is an issue? 
Is it possible to set different encodings for different content types?

**Comment by bengro** [comment]
I hacked my way around it by intercepting the request here: https://github.com/website-scraper/node-website-scraper/blob/27f2639b3715b5eda8a70b0998e8e6c119f047ad/lib/request.js#L63. 

A possible solution would probably involve passing in a mapper function from options, mapping extensions to encodings.

**Comment by s0ph1e** [comment]
Hi @bengro 

Thanks for reporting issue 
You are right, for now it is not possible to use different encodings for different content types. I'll try to find a solution for that. 

I can suggest one more workaround - you can convert to needed encoding using [httpResponseHandler](https://github.com/website-scraper/node-website-scraper#httpresponsehandler) options, something like this:

```javascript
httpResponseHandler: (response) => {
  if (response.headers['content-type'].startsWith('image')) {
     return Promise.resolve(response.body);
  }
  return Promise.resolve(convertToUTF8(response.body));
}
```

**Comment by s0ph1e** [comment]
Added in #308, will be published in next release
