### ISSUE TITLE
Few website don't scrape preparly

### ISSUE THREAD

**Issue by phpsenraj** [website-scraper/node-website-scraper#265]
* **website-scraper version:**
I have used website-scraper@3.3.2
**Please provide your full options object:**
const scrape = require('website-scraper');

var options = {
    urls: ['https://www.beautybay.com/'],
    directory: 'save_as/',
    request: {
        headers: {
            'User-Agent': 'Mozilla/5.0 (Linux; Android 4.2.1; en-us; Nexus 4 Build/JOP40D) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.166 Mobile Safari/535.19'
        }
    },
    sources: [
        {selector: 'img', attr: 'src'},
        {selector: 'link[rel="stylesheet"]', attr: 'href'},
        {selector: 'script', attr: 'src'}
    ],
    subdirectories: [
        {directory: 'img', extensions: ['.jpg', '.png', '.svg']},
        {directory: 'js', extensions: ['.js']},
        {directory: 'css', extensions: ['.css']}
    ],
    updateMissingSources: true,
    ignoreErrors: true,
    onResourceError: (resource, err) => {
        console.log(`Resource  was not saved because of `);
    },
    
};

scrape(options).then((result) => {
    console.log('Website succesfully downloaded');
}).catch((err) => {
    console.log('An error ocurred', err);
});
<details>
<summary>Options</summary>

```js



```

</details>
I have used npm website-scraper and html download working most of the website. But I tried this website https://www.beautybay.com/ can't download and broken (blank) source. So, if any one know let me know what i have changes or mistake my code.
![beautybay_scraper](https://user-images.githubusercontent.com/36505026/36256656-d431fea8-1279-11e8-9282-02ce5d7edecf.png)

**What is expected result?**
Few Website scraper html is not download fully. But lot of website using this same code is working. I can't fix this.
**What is actual result?**
Lot of website using this same code is working. I Like website html save as (css,js,img etc).

**Comment by s0ph1e** [comment]
Hi @phpsenraj 
As I can see this site uses js scripts to render content, by default `website-scraper` doesn't handle it.
I suggest you to try [website-scraper-phantom plugin](https://github.com/website-scraper/node-website-scraper-phantom) for this site, it can handle dynamic content
