### ISSUE TITLE
Wildcard for files subdirectories

### ISSUE THREAD

**Issue by perazzi** [website-scraper/node-website-scraper#272]
This is not an issue, rather a feature request.
I think that the subdirectories is pretty cool. I was trying to keep all the included files separate from the actual index.html file, but if in order to do so, I'd need to create a huge array with all file extensions, pointing to the same directory.
I'd like to suggest a wildcard ".*", so that all files (except index, which would go to would go to *directory*.

So fo example if I said:
```
scrape({
  urls: ['http://example.com'],
  directory: '/path/to/save',
  subdirectories: [
    {directory: 'resources', extensions: ['.*']},
    {directory: 'js', extensions: ['.js']}
  ]
}).then(console.log).catch(console.log);

```
all files would go to /resources, while js files would ggo to /js.

**Comment by s0ph1e** [comment]
Hey @perazzi 
Thanks for suggestion, good idea 👍 
Contributions are welcome

**Comment by perazzi** [comment]
Yeah, I was sketching something to open a PR.. Still getting used to the code
