### ISSUE TITLE
Edit the html of scraped page

### ISSUE THREAD

**Issue by Kashdog** [website-scraper/node-website-scraper#276]
where is the variable in the javascript that stores the html of the fetched scraped page? need to find it so I can modify the content.

**Comment by aivus** [comment]
Hello @Kashdog 

It depends on when you want to have this content.
You can look [here](https://github.com/website-scraper/node-website-scraper#httpresponsehandler) if you want to modify content during scrapping process or [here](https://github.com/website-scraper/node-website-scraper#callback) if you want to get access to fetched files after scrapping.

**Comment by s0ph1e** [comment]
I'm closing this issue. If you have more questions - feel free to reopen issue or create new one
