### ISSUE TITLE
Is subscriber possible?

### ISSUE THREAD

**Issue by a20185** [website-scraper/node-website-scraper#279]
Thank you for providing such a useful tool for downloading a site.

However, when I'm trying using this tool for downloading a not-that-small site with recursive depth set to a high value(i.e. 100), I found it still work , however it would take a really long time to finish this job, performing like a dead process as it **NEVER shows its download status**. Having read the document ,there seemed no way to provide a way for the user to observe the realtime download status.Hence, I'm wondering is it possible to provide the subscriber behavior to get the download status in realtime when performing the recursive downloading status.

(Haven't read the source yet that I cannot know if the strategy is possible or maybe difficult.

**Comment by a20185** [comment]
@aivus

**Comment by s0ph1e** [comment]
Hi @a20185 
You can use [onResourceSaved](https://github.com/website-scraper/node-website-scraper#onresourcesaved) or [onResourceError](https://github.com/website-scraper/node-website-scraper#onresourceerror) callbacks to track what resources were loaded
But it will not show how much resources left to download
