### ISSUE TITLE
Scrape websites generated with JavaScript, like React

### ISSUE THREAD

**Issue by garyking** [website-scraper/node-website-scraper#284]
This module only successfully scrapes websites that are plain HTML. It would be nice to be able to scrape websites that are generated with JS, too, like those written in React.

Puppeteer, on the other hand, can read JS pages, but doesn't have an easy way to download all resources and organize them in dirs, etc., which this module can do.

So it would be nice to be able to plug Puppeteer into this module somehow, to get this functionality.

**Comment by xarantolus** [comment]
Hey Gary,
there is the [`node-website-scraper-phantom` module](https://github.com/website-scraper/node-website-scraper-phantom) that uses [PhantomJS](http://phantomjs.org/), which is similar to Puppeteer, to run JavaScript on downloaded pages.

**Comment by garyking** [comment]
Thanks I'll check it out. At a brief glance, that module looks like very little code, so a version made for Puppeteer might be easy to make.

**Comment by s0ph1e** [comment]
Hi guys 
For now we can use phantom plugin, but it's quite slow (I don't recommend to use it with `recursive` option) and [phantomjs is not supported now](https://github.com/ariya/phantomjs/issues/15344) so in future we might face some issues with it
I think it's good idea to make plugin with puppeteer

**Comment by s0ph1e** [comment]
Added plugin for puppeteer [website-scraper-puppeteer](https://github.com/website-scraper/website-scraper-puppeteer)
