### ISSUE TITLE
Chrome doesn't allow CSS from files that don't end in .css

### ISSUE THREAD

**Issue by garyking** [website-scraper/node-website-scraper#289]
Is it possible to rename CSS files saved by this package to `.css` files? For instance, downloading a page from Wikipedia downloads CSS files with .php, yet Chrome doesn't allow local files to reference CSS files with any extension other than `.css`.

**Comment by s0ph1e** [comment]
Hi @garyking 
By default resource is saved with filename from url, `load.php` for wikipedia for example. 
You can customize it using [filenameGenerator](https://github.com/website-scraper/node-website-scraper#filenamegenerator) option
For example:
```javascript
scrape({
  urls: ['http://example.com'],
  directory: '/path/to/save',
  filenameGenerator: (resource, options, occupiedFileNames) => {
    if (resource.isCss()) {
        return 'style.css';
    } 
    return getOtherNameForResource();
  }
})
```

Original filenameGenerator can be found in [lib/filename-generator/by-type.js](https://github.com/website-scraper/node-website-scraper/blob/798a0f0a8c314074ca3e109203e4c4e3a69ff5a1/lib/filename-generator/by-type.js)
