### ISSUE TITLE
can i crawl pdf?

### ISSUE THREAD

**Issue by cucr** [website-scraper/node-website-scraper#293]
* **website-scraper version:**

**Please provide your full options object:**

<details>
<summary>Options</summary>

```js



```

</details>

**What is expected result?**

**What is actual result?**

**Comment by s0ph1e** [comment]
Hi @cucr 

Yes, it is possible to download pdf

* If you want to download some html that contains links to pdfs (usually `<a href="document.pdf">`) you can use [recursive](https://github.com/website-scraper/node-website-scraper#recursive) option and all resources from `<a ..>` tag will be downloaded

* If you want to download only 1 pdf, you can use its url  in [urls](https://github.com/website-scraper/node-website-scraper#urls) option to download it
```
urls: [{url: 'http://example.com/document.pdf', filename: 'document.pdf'}],
```
