### ISSUE TITLE
modify the final index.html file before saving it

### ISSUE THREAD

**Issue by milabron** [website-scraper/node-website-scraper#296]
* **website-scraper version:**
3.3.6

**What is expected result?**

To be able to modify the final file "index.html" before saving it, because doing it with "httpResponseHandler" is not what I need because I also want to apply encode and make replacements in the HTML con `Cheerio`, and with "saveResource" it forces me to build the complete function, and I just want to treat the index.html file.

**What is actual result?**
The current result forces me to rebuild the "saveResource" function.

**Comment by chiqui3d** [comment]
Well I realized that with `onResourceSaved`, I can open the file and rewrite it with the fs module.

I also realized that if you use `phantom`(options.httpResponseHandler=phantomHtml;), the `httpResponseHandler` function, it doesn't work.
