### ISSUE TITLE
Keep assets under the same original path

### ISSUE THREAD

**Issue by hackhat** [website-scraper/node-website-scraper#298]

**Comment by s0ph1e** [comment]
Hi @hackhat 
Could you please explain what do you mean? 
Some examples with expected result will be nice

**Comment by hackhat** [comment]
Sorry about that. 

Let's say my website is:

 - folder1/folder2/file.js

Your scrapper exports to:

 - js/file.js

Path not the same, problematic sometimes. Especially if some css file might include some other file or some other strange things you can't foresee. Or maybe simply if you do a wordpress clone, you can copy the whole wp-content to make sure nothing is missing, or old assets can be accessed even if no html page links to that asset.

**Comment by s0ph1e** [comment]
Hey @hackhat 
Did you try `filenameGenerator: 'bySiteStructure'` option? Please see description is in readme. It should help

**Comment by hackhat** [comment]
Ok, thanks
