### ISSUE TITLE
[rfc] Add custom getData, setData for custom cases

### ISSUE THREAD

**Issue by Boorj** [website-scraper/node-website-scraper#301]
Often images are used as background image. Scraper uses cheerio and css/jquery selectors `$(rule.selector)` , and doesn't extract (and save modified) partial urls from `background-image: url(...)`. 
[This code](https://github.com/website-scraper/node-website-scraper/blob/master/lib/resource-handler/html/html-source-element.js#L33-L44) seems only to work with solid attributes, not parts.
Is there a known over workaround to extract _inlined_ `style="background-image:url('URL')"`?

**Comment by Boorj** [comment]
I think, this code could be a nice addition, that solves the problem and doesn't break any BC:

```js
getData () {
    if ((typeof this.rule.getData === 'function') && (typeof this.rule.setData === 'function')) {
        return this.rule.getData(this.el);
    }

    // old code
}

setData (newData) {
    if ((typeof this.rule.getData === 'function') && (typeof this.rule.setData === 'function')) {
        this.rule.setData(this.el, newData);
        return;
    }

    // old code
}
```

Each rule could have it's own `getData` + `setData`.
`getData` receives element as argument, and returns a text.
`setData` receives element + newData as arguments, and injects the string back.

**Comment by Boorj** [comment]
I'm sorry, @s0ph1e, i haven't noticed [style] parsing with [CssText parser](https://github.com/website-scraper/node-website-scraper/blob/master/lib/resource-handler/html/html-source-element.js#L9). The problem was that i redefined sources, and it dropped the defaults one.
So everything works perfectly now. 
But this is still a question: can you expose `containerClass` or add support for custom extractors? That could be very useful for complex cases.

**Comment by s0ph1e** [comment]
Hey @Boorj 
Great that it works for you now.

Could you please provide an example of such complex case? Maybe it would be better to improve existing functionality (I believe there are limited amount of cases on websites that should be handled) instead of exposing that?

**Comment by Boorj** [comment]
Sometimes resource (i.e. image url) is put into json inside data-* attribute. 
Actually, i used webscraper to extract webpages from Tilda.  And they put image urls for js plugins into attributes, but directly (url only inside attribute).  So for my task standard functionality of webscraper was enough.  I can clearly see some situations, when demanded data is placed inside tag attribute, but with some extra chars around data. Also this solution with custom getData, setData seems to be quite simple and usefull in those cases.

But i don't have any good exact example. So, please feel free to close this issue :)

**Comment by s0ph1e** [comment]
Thanks for suggestion, I'll consider adding this functionality in future release

**Comment by Boorj** [comment]
Thank you, Sophia
