### ISSUE TITLE
scrapping web page from wrong domain

### ISSUE THREAD

**Issue by jns4u** [website-scraper/node-website-scraper#310]
Detail::
Using website scrapper I have created a module to scrap data and uploading to corresponding aws s3 bucket. This feature work fine on development machine but when tested same feature on production server found irrespective of url submitted get scrapped data from same domain "http://www.bellygraph.com/"

Version: 3.3.7

Snippet:
Issue seems to in promise code block given below that initiates scrapping
const options = {
  urls: ['http://nodejs.org/'],
  directory: '/path/to/save/',
};

// with promise
scrape(options).then((result) => {
	/* some code here */
}).catch((err) => {
	/* some code here */
});

expected result should scrapped home page of node website i.e. 'http://nodejs.org/'

getting scrapped data for home page of "http://www.bellygraph.com/"

**Comment by s0ph1e** [comment]
Hi @jns4u 

Unfortunately I can not know why does it work on one environment and does not work on another. Maybe there is some differences in firewall setup or target website returns different content depending on IP - there may be plenty of reasons.

I can suggest to [enable logs](https://github.com/website-scraper/node-website-scraper/blob/master/README.md#log-and-debug) on environment with issue and find what happens and why does it downloads data from wrong domain - maybe it will help

**Comment by s0ph1e** [comment]
Good that you found the reason, looks like it was specific to aws s3

I'm not sure that I can suggest something, for different environments different actions required. For me it worked fine when deploying to simple digital ocean server, no additional setup was needed
