### ISSUE TITLE
Freeze when scraping recursively

### ISSUE THREAD

**Issue by MikeVrana** [website-scraper/node-website-scraper#313]
* **website-scraper version: 3.3.7**

**Please provide your full options object:**

<details>
<summary>Options</summary>

```js
{
    urls: ['http://www.dhl.com/en.html'],
    directory: './downloads/',
    recursive: true,
    maxRecursiveDepth: 3,
    ignoreErrors: false
}
```

</details>

**What is expected result?**
http://www.dhl.com/en.html scraped recursively to depth 3
**What is actual result?**
Nothing, the scraper freezes without saving anything. It freezes at different pages when changing ```requestConcurrency```.
Thanks in advance for taking your time to fix this issue.

**Comment by s0ph1e** [comment]
Hi @MikeVrana 
Looks like scraper tries to download too much pages and freezes. 

I'd suggest to 
* ensure that you're trying to download only what you need. To track what scraper is doing you can use `debug` [as described in readme](https://github.com/s0ph1e/node-website-scraper#log-and-debug)
* add urlFilter and/or decrease maxRecursiveDepth
* increase memory limit for node process

Hope it helps
