### ISSUE TITLE
Set default behavior of ignoreErrors to false? 

### ISSUE THREAD

**Issue by KingZee** [website-scraper/node-website-scraper#327]
It's more intuitive to set it to false because errors shouldn't be ignored by default. :) 
It took me way too long to understand why my Promise.reject() wasn't working.

I could make a pull request but this is more of an agreement issue, if you have any reasons on why it shouldn't be that way I'm open to discussion.

**Comment by s0ph1e** [comment]
Hi @KingZee

Thank you for feedback!
Initially the reason to ignore errors was to download as much as possible

But now I agree that it may be confusing.
I'm going to update it in next major version and probably rethink what is an error and what is expected behavior

**Comment by s0ph1e** [comment]
ignoreErrors = false will be default option in next major release, thanks for suggestion 👍
