### ISSUE TITLE
Irregular behviour: Sometimes it grabs almost complete site, sometimes it just grabs one page  and throws no error, sometimes it just runs out of memory after several logs of 'socket hangs up' or 'phantomjs crashed with error <errorcode>'

### ISSUE THREAD

**Issue by k-disaster** [website-scraper/node-website-scraper#330]
Can not provide logs for privacy reasons. I am working from behind proxy and I am using http-proxy-agent package to set proxy in request options. I am also using 'website-scraper-phantom' as I'm scraping dynamic sites. 

### Configuration
**version:** [3.3.7]

**options:** [
 {

    // URLs to visit
    urls: [<someurl>],

    // Directory to save downloaded content
    directory: './',
// Sub-directories to arrange static files
    subdirectories: [{
            directory: 'img',
            extensions: ['.jpg', '.png', '.svg', '.gif']
        },
        {
            directory: 'js',
            extensions: ['.js']
        },
        {
            directory: 'css',
            extensions: ['.css', '.scss']
        },
    ],

    // Enable recursive download
    recursive: true,

    // Depth of crawling
    maxDepth: 2,

    //Ignores errors if any
    ignoreErrors: false,

    // Request options
    request: {
        // Setting agent here. It has the proxy set
        agent: agent,
        headers: {
            'User-Agent': 'Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko)'
        }
    },

    // Maximum request at a time
    requestConcurrency: 100,

    //Prettifies URLs
    prettifyUrls: true,

    // File names generation scheme
    filenameGenerator: 'bySiteStructure',

    // HttpResponseHandler
    httpResponseHandler: phantom,

    // On resource saved
    onResourceSaved: (resource) => {
        console.log(`\nResource ${resource} was saved to fs`);
    },

    // On resource Error
    onResourceError: (resource, err) => {
        console.log(`\nResource ${resource} was not saved because of ${err}`);
    },

    // Filters out crawl frontier based on base crawling url (seed)
    urlFilter: function (url) {
        // If url contains the domain of the website, then continue:
        if (url.indexOf(options.urls[0]) === 0)
            return true;
        else
            return false;
    }
};
]
```js


### Description

[Irregular behviour: Sometimes it grabs almost complete site, sometimes it just grabs one page  and throws no error, sometimes it just runs out of memory after several logs of 'socket hangs up' or 'phantomjs crashed with error <errorcode>'
Some other websites are being scraped absolutely fine; but these specific sites which are behind a gateway are causing issues.
I have added proxy,'User-Agent' and cookies properly with which the request is supposed to cross the gateway.]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

### Additional Information

[Any additional information configuration or data that might be necessary to reproduce the issue]

**Comment by s0ph1e** [comment]
Hi @k-disaster 

I think errors may occur because of
* `website-scraper-phantom` module does not support proxies.
  Scraper makes 1st request with `request` module (which supports proxy) and if response is html - it makes second request with phantom plugin (which does not support proxy). There is [pull request](https://github.com/website-scraper/node-website-scraper-phantom/pull/2) for proxies, work is not finished there but you can try it
* phantomjs is not very stable and sometimes it crashes

Is it more stable if use without proxy?

**Comment by k-disaster** [comment]
Hey, thanks. Will let you know if it works.

**Comment by k-disaster** [comment]
Yes it is stable when used without proxy. I mean on other web applications. The one I want to scrape doesn't allow to scrape without proxy.

**Comment by s0ph1e** [comment]
Hi @k-disaster 

Did you try to install `website-scraper-phantom` plugin from this [pull request](https://github.com/website-scraper/node-website-scraper-phantom/pull/2)? Does it work?

**Comment by k-disaster** [comment]
Hi, apologies for the late response.
I did't install the plugin from the 'pull request' but dis the changes manually. I didn't make situation any better.
