### ISSUE TITLE
Add option to suppress error when directory exists

### ISSUE THREAD

**Issue by iFwu** [website-scraper/node-website-scraper#333]
### Description
There're some situations that I want to scrape multiple organized pages to one directory, but it will throw an error.
So, is possible to add an option to suppress the error when directory exists(though I can delete the code of throwing error)?
PS:
The reason why I don't use `[url1, url2, ...]` in `urls` option is that I want fully control of the scrapping process, like use 'promise-limit' to limit the concurrency and resume scraping after break.

**Comment by s0ph1e** [comment]
You can use [resourceSaver](https://github.com/website-scraper/node-website-scraper/blob/3.x/README.md#resourcesaver) option to overwrite default behavior and save to existing directory.

But be aware that saving to existing directory may include next tricky things:
* resolving conflicts between generated filenames and existing files
* handle corner cases like different access rights to files and directories, symlinks, etc.
