### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by thoughtsunificator** [website-scraper/node-website-scraper#341]
## context
node-website-scraper version: **3.4.0** (i dont wish to upgrade)
node -v: 

> v11.0.0

## myscript.js
```
const scrape = require('website-scraper')
const logger = require('tracer').dailyfile({ root: 'logs', maxLogFiles: 10, allLogsFileName: 'directory' })
scrape({
  urls: ['http;//example.com'],
  recursive: true,
  request: {
      headers: {
        'User-Agent': 'best browser',
        "Cookie": "best cookie"
      },
  },
  ignoreErrors: true,
  directory: 'directory',
  requestConcurrency: 10,
  onResourceSaved: (resource) => logger.log(`Resource ${resource.filename} was saved to fs`),
  onResourceError: (resource, err) => logger.error(`Resource ${resource.filename} was not saved because of ${err}`)
})
```
## error

> <--- Last few GCs --->
> 
> [1464:0000000000482BB0] 16506847 ms: Mark-sweep 1309.9 (1427.6) -> 1307.9 (1427.6) MB, 92.7 / 0.0 ms  (average mu = 0.181, current mu = 0.093) allocation failure scavenge might not succeed
> [1464:0000000000482BB0] 16506955 ms: Mark-sweep 1309.9 (1427.6) -> 1308.0 (1427.6) MB, 94.5 / 0.0 ms  (average mu = 0.157, current mu = 0.131) allocation failure scavenge might not succeed
> 
> 
> <--- JS stacktrace --->
> 
> ==== JS stack trace =========================================
> 
>     0: ExitFrame [pc: 000000283CF50361]
>     1: StubFrame [pc: 000000283CF516A1]
> Security context: 0x00c90709d969 <JSObject>
>     2: /* anonymous */ [0000021FC4813589] [C:\Users\xxx\node_playground\node_modules\psl\index.js:~141] [pc=000000283F527044](this=0x0209f01a7969 <Object map = 000000FA932EC471>,0x02b11e308189 <String[19]: www.example.com>)
>     3: /* anonymous */ [0000021FC4815F01] [C:\Users\xxx\node_playground\node_modules...
> 
> FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
>  1: 000000013F28D945
>  2: 000000013F265EE6
>  3: 000000013F2668D0
>  4: 000000013F6A677E
>  5: 000000013F6A66B7
>  6: 000000013F97C724
>  7: 000000013F9723CE
>  8: 000000013F970AC8
>  9: 000000013F97A3A7
> 10: 000000013F97A426
> 11: 000000013F53E951
> 12: 000000013FC8EF92
> 13: 000000283CF50361

**Comment by aivus** [comment]
Hi @thoughtsunificator 

Try this: https://github.com/website-scraper/node-website-scraper/blob/master/docs/FAQ.md#q-website-scraper-freezesruns-out-of-memorydoes-not-download-my-website

**Comment by thoughtsunificator** [comment]
@aivus The error happened while download really simple html pages in thousands so anything mentioned there won't be of much help.

**Comment by thoughtsunificator** [comment]
I should mention that i got a

> (node:3984) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 pipe listeners added. Use emitter.setMaxListeners() to increase limit

way before the fatal error happened

**Comment by aivus** [comment]
According to `JavaScript heap out of memory` in error message that means nodejs process run out of memory.

We need a proper STR to reproduce it (with real URL). Otherwise it's impossible to reproduce.

Btw, feel free to debug and create PR with fix if you know why it happens.

**Comment by thoughtsunificator** [comment]
I am going to use Java, JavaScript is not for me this time =) thanks for the help and the great package.
