### ISSUE TITLE
bySiteStructure but keep references untouched

### ISSUE THREAD

**Issue by tolmasky** [website-scraper/node-website-scraper#342]
### Configuration
**version:** 4.0.0

**options:** 
```js
{ 
        urls: [...],
        filenameGenerator: "bySiteStructure"
}
```
### Description

If you use `bySiteStructure`, the URLs in the HTML will helpfully be replaced with relative paths to the files downloaded onto the system. In my configuration however, I am actually replicating and proxying the domains when I launch these statically reproduced sites, so I'd like the URLs to remain untouched. For example, the following dummy HTML:

```html
<img src = "https://something-else.com/a.gif">
```

would be turned into:

```html
<img src = "../something-else.com/a.gif">
```

However, I'd like it to just remain "https://something-else.com/a.gif" instead. I'm hoping there is an option, or simple change I could make to the bySiteStructure plugin, to do this.

**Comment by s0ph1e** [comment]
Hi @tolmasky

I can suggest to implement custom plugin with [getReference](https://github.com/website-scraper/node-website-scraper/blob/master/README.md#getreference) action. There your can check domain of resource and return its original absolute url 

Hope it helps
