### ISSUE TITLE
Adding urls mid-download

### ISSUE THREAD

**Issue by harzzn** [website-scraper/node-website-scraper#351]
Hi there, is it currently possible to add more urls to the list of urls that will be downloaded during the download?

I would like to:
1) Retrieve the robots.txt, parse it for the location of the website sitemap
2) Get the sitemap and parse that for links to pages
3) Add the pages to the list of urls to be downloaded

Ideally all of this would happen asynchronously while the download of the rest of the website has already been started.

Retrieving and parsing those extra files is not really an issue, but it would be great if it would be possible to use the plugin-framework to get those files, process them and then somehow add the page urls mid-download to the list of urls that will be downloaded.

I understand that those urls would usually be found anyway through links but I would like to do it anyway to make sure no content is missing. I've only been able to come up with getting those links before the download or some other pretty hacky ideas on how to do this so I'm wondering if there is a nice and clean way to do this?

**Comment by harzzn** [comment]
I might have been overthinking this issue and should just do it synchronously. Anyway it would be interesting to know if the is a away to add any urls mid-download? Let's say for example if I would like to parse some urls from some text or e.g. javascript on a page (so the urls can't be retrieved with css rules) and add them to the list of urls to download.

Let me know if a clearer explanation of what I'm after is needed.

**Comment by s0ph1e** [comment]
Hey @harzzn 👋

For now it is not possible to add resources to queue for downloading in the middle of execution, only resources found by module can be downloaded.

I can only suggest to add needed urls to initial `urls` option (if you know them)
