### ISSUE TITLE
After adding 'recursive', will the process not stop?

### ISSUE THREAD

**Issue by sparksworld** [website-scraper/node-website-scraper#352]
After adding 'recursive', will the process not stop?

**Comment by s0ph1e** [comment]
Hi @sparksworld 👋 

It stops after download everything from queue. Queue size depends on other options. 
If you use recursive - don't forget to set `maxRecursiveDepth` to avoid infinite downloading and `urlFilter` to filter out not needed resources.

Here is an [explanation for maxRecursiveDepth option](https://github.com/website-scraper/node-website-scraper/blob/master/docs/FAQ.md#q-what-maxdepth-maxrecursivedepth-should-i-use)

**Comment by sparksworld** [comment]
@s0ph1e 
Thank you for your tips, this is very helpful to me.

**Comment by s0ph1e** [comment]
Happy to help 🙂
If you have more questions - feel free to open new issues
