### ISSUE TITLE
Duplicate html page

### ISSUE THREAD

**Issue by christophebe** [website-scraper/node-website-scraper#356]
Hi all, 

With the previous code, I got duplicate pages for some of them (eg. mypage.html & mypage_1 whith the same content). Is it possible to avoid that ? 

const options = {
     urls: [ WEBSITE_URL ],
     directory: OUTPUT_DIR,
     recursive: true,
     urlFilter(url) {
       console.log(`downloading : ${ url }`);
       return url.includes(WEBSITE_URL);
     }
    await scrape(options);
};

Thanks

**Comment by christophebe** [comment]
Sorry for the noise ! I was an issue on the website I am trying to download

**Comment by s0ph1e** [comment]
Hey @christophebe 👋

Feel free to open new issues if you have more questions
