### ISSUE TITLE
Unable to scrap from special character URL's 

### ISSUE THREAD

**Issue by WagnerSilveira** [website-scraper/node-website-scraper#360]
### Configuration
**version:** "4.0.1"

**options:** 

```js

const ops = {
    urls: ['https://' + baseDomain],
    directory: destination,
	sources: [
		{selector: 'img', attr: 'src'},
		{selector: 'img', attr: 'srcset'},
		{selector: 'img', attr: 'data-src'},
		{selector: 'img', attr: 'data-lazy'},
		{selector: 'link[rel="stylesheet"]', attr: 'href'},
		{selector: 'script', attr: 'src'}
	],
	
	urlFilter: function(url) {

		for(let i = 0; i <= domains.length; i++) {

			// está em domínio mapeado?

			if(url.indexOf('//'+domains[i]) != -1) {

				// é um arquivo?

				var parts = url.split('/');

				if(parts[ parts.length - 1].indexOf('.') != -1) {

					console.log('-> ' + url);
					return true;

				}

			}

		}

	   	return false;

 	},
	recursive: true,
	ignoreErrors: true,
	requestConcurrency: 6,
	filenameGenerator: 'bySiteStructure',
	maxRecursiveDepth: 16,
	maxDepth: 16,
    plugins: [ new PuppeteerPlugin() ]
};

```

### Description

Request path contains unescaped characters
url: https://mydomain/themes/lp-homolog/assets/images/versão1.png"

**Expected behavior:** Put in the queue to download file

**Actual behavior:** Skip file download, and return this error in file scrapper.js, line 194
Request path contains unescaped characters
ERR_UNESCAPED_CHARACTERS

**Comment by s0ph1e** [comment]
Hi @WagnerSilveira 
Thanks for reporting, I'll take a look on this issue and PR in nearest few days

**Comment by s0ph1e** [comment]
Hey @WagnerSilveira 

I've tried to reproduce this problem by downloading webpage with diacritics - https://de.wikipedia.org/wiki/FC_Bayern_München with links to resources that also contain diacritics in url and it worked fine for me - page and resources was downloaded and can be opened locally.

```javascript
let options = {
	urls: ['https://de.wikipedia.org/wiki/FC_Bayern_München'],
	directory: 'tmp/' + new Date().getTime(),
};

async function downloadWebsite() {
	const result = await scrape(options);
	console.log('RESULT: ', result);
}

downloadWebsite();
```

Could you please share real link to failed resource? Does it work after your fix (I mean real resource returned, non 404)?

**Comment by WagnerSilveira** [comment]
It occurs while scraping the whole website, not in the requested URL

**Comment by s0ph1e** [comment]
As I mentioned before - I've tried website which contains resources with diacritics (not only main url with diacritics) and it worked fine

That's why I'm asking for reprodusable examples with such problem
