### ISSUE TITLE
Rewrite file if exists

### ISSUE THREAD

**Issue by botaniQQQ** [website-scraper/node-website-scraper#370]
Hello.

How to rewrite file if exists?

![5ArgoeT](https://user-images.githubusercontent.com/3118010/62329453-94846000-b4be-11e9-8ad8-b0b45b91dea0.png)

**Comment by s0ph1e** [comment]
Hi @botaniQQQ

If files have same url - scraper will not create duplicated file. If urls are different, for example `http://domain-one.com/style.css` and `http://domain-two.com/style.css` - it will save files to `style.css` and `style_1.css` 

Could you please check if that files have different urls or not?
