### ISSUE TITLE
Is there a way to not re-save files common to multiple scrapes?

### ISSUE THREAD

**Issue by AramZS** [website-scraper/node-website-scraper#376]
I am scraping from a series of sites that share particular script urls.

I have a configuration that includes 
```javascript
        subdirectories: [
            {directory: '../scripts', extensions: ['.js']}
        ],
```

From what I can tell, if I scrape website a.com that contains a reference to `<script src="b.com/script-foo.js">` and website c.com that contains the same reference to `<script src="b.com/script-foo.js">` with this configuration, I'll get the file saved to `../scripts/script-foo.js` twice. However, I know that `script-foo.js` is a unique name shared among multiple pages. `script-foo.js` will always have the exact same content on every scrape.

What I'd like to do is make it so that if `../scripts/script-foo.js` already exists, the scrape operation doessn't write that file. There seemed to be a number of hooks that get most of the way there, but I couldn't see a way to do this. Am I missing something or is this a feature request?

Thanks!

**Comment by s0ph1e** [comment]
Hi @AramZS 

Same resource should not be saved twice if resource urls are equal (including query params). If it's saved twice - may be urls are not completely the same or it's a bug.
Could you please provide reproducible example where script is saved twice so that I can check it?
