### ISSUE TITLE
Option to prevent removal of base elem

### ISSUE THREAD

**Issue by abhishekgupta-1** [website-scraper/node-website-scraper#381]
The website I'm scraping contains 

`<base href="path/to/somewhere" />`

Scraper removed the above element and changes all the relative paths in the html file. E.g.
`<script src='script.js'></script>`
changes to 
`</script src='path/to/somewhere/script.js'></script>`

The relative paths in javascript which rely on the base break and not downloaded. E.g.

`$.getScript('../js/script.js', function () {});`

should have been resolved to

`$.getScript('path/to/js/script.js', function () {});`

**Comment by s0ph1e** [comment]
Hi @abhishekgupta-1 👋 

Sorry for late response. Base tag is removed to have correct paths (to local resources) in result html. Even if `base` was not removed - it will not update paths in javascript, website-scraper can only update html and css files, see [details here](https://github.com/website-scraper/node-website-scraper/blob/master/docs/FAQ.md#q-why-website-with-javascript-is-not-downloaded-correcly). To avoid that you can try to use phantom or puppeteer extensions.

I you face some bugs or have some suggestions - feel free to open new issues
