### ISSUE TITLE
How to store or log images, instead of downloading?

### ISSUE THREAD

**Issue by 1997-10** [website-scraper/node-website-scraper#382]
When I run the script, everything is getting saved in local folders. I want to store the output in a variable and use it in another method. How can I do it?

**Comment by s0ph1e** [comment]
Hi @1997-10 
Sorry for late response.

You can overwrite saving resources with custom plugin and action `saveResource` (to ignore saving) and `onResourceSaved` (to add each resource to variable) 

It can be something like this:
```javascript
class MyPlugin {
	apply(registerAction) {
		registerAction('saveResource', ({resource}) => {/* do nothing here */});
		registerAction('onResourceSaved', ({resource}) => {/* add resource to variable here after it was saved */});
	}
}

scrape({
  urls: ['http://example.com/'],
  directory: '/path/to/save',
  plugins: [ new MyPlugin() ]
});
```

You can find more details about plugins and parameters here https://github.com/website-scraper/node-website-scraper#plugins

Hope it helps. If you have more questions - feel free to ask
