### ISSUE TITLE
Add console progress logging 

### ISSUE THREAD

**Issue by Pomax** [website-scraper/node-website-scraper#385]
Running the following code shows zero output on the console _and_ doesn't write files until it's done. That's a pretty horrible way of having to trust things are working:
```
const scrape = require('website-scraper');
const PhantomPlugin = require('website-scraper-phantom');

scrape({
    urls: ['https://www.image-line.com/support/flstudio_online_manual/'],
    directory: './data',
    recursive: true,
    maxRecursiveDepth: 2,
    plugins: [ new PhantomPlugin() ]
}); 
```
Would it be possible to get console logging that says which URLs are currently being downloaded, eg. using a `logProgress: true` option?

**Comment by s0ph1e** [comment]
Hi @Pomax 

There are several options to diplay progress:

1. You can add environment variable to see logs as described [here](https://github.com/website-scraper/node-website-scraper#log-and-debug)
```
export DEBUG=website-scraper*; node app.js
```


2. or you can write your own plugin which logs what you need, see details in [plugins section in readme](https://github.com/website-scraper/node-website-scraper#plugins)

Hope it helps

**Comment by Pomax** [comment]
Those are not really an option on Windows without adding lots of additional packages, though. As core functionality for any utility (anything that takes a long time should have a progress indicator =) and the fact that the scraper already takes an options argument, having an option for this makes far more sense.

It doesn't need to be an estimating progress that says we're at, "45%", just something that shows that the utility is actually _doing_ something instead of now showing anything at all, with the only sign that it's even still working that its process has CPU activity and the memory footprint keeps changing.

Rather than "debug", it would be useful to have a "verbose" option (an almost universal flag among command line utilities), so you could do this:

```
const scrape = require('website-scraper');

const options = {
  urls: ['http://nodejs.org/'],
  directory: '/path/to/save/',
  verbose: true
};

const result = await scrape(options);
```

And then people would be free to pull that value from anywhere they like. `process.env.VERBOSE`, or `process.args[ process.args.findIndex(`-v`)+1 ]`, etc.

**Comment by s0ph1e** [comment]
As for Window - [debug readme has some examples how to run it on Windows](https://github.com/visionmedia/debug#windows-command-prompt-notes) - I haven't tried it but hope it works

I agree that displaying progress is useful and there are 2 options to have it - debug env variable and writing plugin where you can log exactly what's needed for your task.

Not sure that I want to add new `verbose` or `debug` props to options object. It's great to have `--verbose` for CLI tool - it's standard way of logging there. But website-scraper is js package, not CLI tool, and for js packages standard way is using `debug` module I guess. I think better logging can be done using plugins functionality - developers will be able log only events that needed + write logs not only to console, but to other places.

I'm still considering what can be done for logging and will be happy to see more ideas/thought about it.

**Comment by Pomax** [comment]
debug and verbose are semantically differnt, though. With debug, you want to see "everything" including passed over exception, content inspection, etc., which is not true for a verbose mode, which should only show "everything meaningful".

So here's an idea: it's pretty strandard for code to offer logging, at several levels. What about a `LOGGING` option instead, that can be set to `DEBUG` or `WARN` or `INFO` so that the level and volume of logging can be controlled?
