### ISSUE TITLE
Sources with img-srcset

### ISSUE THREAD

**Issue by meceware** [website-scraper/node-website-scraper#394]
Hi,

Great library! Thank you for your time. 

I'm trying to parse `img` tag with `srcset` attribute set. I think I need to parse it somehow but `sources` option do not get a function. Is there a way to include `srcset` URL's?

```
{selector: 'img', attr: 'src'}
```

Thank you,

**Comment by s0ph1e** [comment]
Hey @meceware 👋 

Images with srcset will be downloaded if you use default configuration or you can use 
```
		{ selector: 'img', attr: 'src' },
		{ selector: 'img', attr: 'srcset' },
```
for `sources` option

**Comment by meceware** [comment]
Yeah, I should have tried it before writing this issue :) Thank you for your help, it works great.

Cheers,
