### ISSUE TITLE
Is there a way NOT to change links href inside html or at least an option to control the string that is being replaced to?

### ISSUE THREAD

**Issue by SilencerWeb** [website-scraper/node-website-scraper#395]

**Comment by s0ph1e** [comment]
Hi @SilencerWeb 

Sorry for late response. You can use plugin with [getReference](https://github.com/website-scraper/node-website-scraper/blob/master/README.md#getreference) action to change generated link to resource

Hope it helps

**Comment by SilencerWeb** [comment]
Yeah, that's how I solve it, thanks :)
