### ISSUE TITLE
unhandled rejection, no stack trace

### ISSUE THREAD

**Issue by kevzettler** [website-scraper/node-website-scraper#396]
### Configuration
**version:** [result of `npm ls website-scraper --depth 0` command]

```
├── node-site-downloader@1.3.0
└── website-scraper@4.2.0
```

**options:** [provide your full options object]
```js

const scrape = require('website-scraper')

scrape({
  urls: [
    'http://www.littlewargame.com',
  ],
  directory: __dirname + '/littlewargame',
  recursive: true,
  maxRecursiveDepth: 10,
  request: {
    headers: {
      'User-Agent': 'Mozilla/5.0 (Linux; Android 4.2.1; en-us; Nexus 4 Build/JOP40D) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.166 Mobile Safari/535.19'
    }
  },
  ignoreErrors: true,
})
  .then((error, result) => {
    if(error) throw error;
    console.log('**********result*********', result);
  });

```

### Description
running `DEBUG=website-scraper* node ./scraper.js` with the above script fails with unhandled rejection
```
  website-scraper:debug run 0 actions onResourceSaved +1ms
  website-scraper:info downloading is finished successfully +1ms
  website-scraper:debug run 0 actions afterFinish +0ms
Unhandled rejection (<{ url: "https://www.littlewargame.com/...>, no stack trace)
```
[Description of the issue]

**Expected behavior:** [What you expect to happen]
Should give information on what request if failed on

**Actual behavior:** [What actually happens]
Fails with out any error output 
### Additional Information

[Any additional information, configuration or data that might be necessary to reproduce the issue]

**Comment by s0ph1e** [comment]
Hi @kevzettler 👋

Thank you for reporting issue

I can suggest to decrease `maxRecursiveDepth` to 3 or less and add `urlFilter` as described in [FAQ](https://github.com/website-scraper/node-website-scraper/blob/master/docs/FAQ.md#q-website-scraper-freezesruns-out-of-memorydoes-not-download-my-website)

If it didn't help - I'll try to take closer look on this error

**Comment by kevzettler** [comment]
thanks @s0ph1e 

I have updated the script to be


```
const scrape = require('website-scraper')

scrape({
  urls: [
    'http://www.littlewargame.com',
  ],
  directory: __dirname + '/littlewargame',
  recursive: false,
  maxRecursiveDepth: 3,
  urlFilter: function(url) {
    return url.indexOf('http://www.littlewargame.com') === 0;
  },
  request: {
    headers: {
      'User-Agent': 'Mozilla/5.0 (Linux; Android 4.2.1; en-us; Nexus 4 Build/JOP40D) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.166 Mobile Safari/535.19'
    }
  },
  ignoreErrors: true,
})
  .then((error, result) => {
    if(error) throw error;
    console.log('**********result*********', result);
  });
```

And still encountering the error. 

my versions are

```
kevs-mbp:radcade kevzettler$ node -v
v8.11.4
radcade@1.0.0 /Users/kevzettler/code/radcade
└── website-scraper@4.2.0
```

**Comment by s0ph1e** [comment]
Hi again @kevzettler 

That happens because you use `(err, result) => {}` inside promises `then` method. Promises expect to receive only 1  argument `result` in `then` and only 1 argument `error` in `catch` method. 
Try to update you code to something like:
```javascript
	scrape(options).then((result) => {
		console.log('**********result*********', result);
	}).catch((error) => {
		console.log('**********error*********', error);
	});
```

**Comment by kevzettler** [comment]
thanks @s0ph1e my mistake!
