### ISSUE TITLE
`request` is deprecated

### ISSUE THREAD

**Issue by Richienb** [website-scraper/node-website-scraper#401]
The `request` package has been deprecated and should be replaced with another suitable package such as `got`.

**Comment by s0ph1e** [comment]
Hi @Richienb 

Thank you for suggestion 👍 

I don't mind updating deprecated dependency. 
It can be done only for next major version of this module. `website-scraper` relies on `request`'s api and some options like [request](https://github.com/website-scraper/node-website-scraper#request) and plugins should be re-written.

relates to https://github.com/request/request/issues/3142
