### ISSUE TITLE
cannot scrape css stylesheets ONLY

### ISSUE THREAD

**Issue by kriskate** [website-scraper/node-website-scraper#404]
### Configuration
**version:** [result of `npm ls website-scraper --depth 0` command]
website-scraper@4.2.0 
**options:** [provide your full options object]
```js
{
      urls: [magentoURL],
      directory,
      sources: [
        // { selector: "img", attr: "src" },
        { selector: 'link[rel="stylesheet"]', attr: "href" },
        // { selector: "script", attr: "src" },
      ],
    }

```

### Description

[Description of the issue]

**Expected behavior:** [What you expect to happen]
scrape only the css files

**Actual behavior:** [What actually happens]
it scrapes everything, img and script too

### Additional Information
if you only allow either script or img scraping, it works as expected
if you don't wildcard [rel="stylesheet"], it will get all the <link> tags

I actually have a selfcalled function (function)(), and trying to run with DEBUG-website-scraper but no verbose is shown

package.json: `"scrape:legacy": "DEBUG=website-scraper=1 yarn clean && node -r ./env_loader.js config/scrapeProduction"`

**Comment by s0ph1e** [comment]
Hi @kriskate 👋 

As for debug - environment variable should be `DEBUG=website-scraper*` and not `DEBUG=website-scraper=1`

Please provide website-scraper log received with DEBUG env variable or exact url where I can reproduce this behavior.

Also please note that css stylesheet may contain images in `background-url` rules that will be downloaded by scraper.

**Comment by kriskate** [comment]
woah, my bad, the images being pulled are indeed from within the css files.

`DEBUG=website-scraper*` doesn't show debug info though, when calling as described

Thanks for the help!
