### ISSUE TITLE
Scraping sites with lazyload srcset imags

### ISSUE THREAD

**Issue by graemec23** [website-scraper/node-website-scraper#405]
im trying to scrape a site that has its images lazyloaded and defined by srcset rather than img and at the moment its not getting these images. Is there any option or something i need to specify to get these images?

**Comment by s0ph1e** [comment]
Hi @graemec23 👋 

if you didn't overwrite `sources` option - images from srcset will be downloaded automatically.
if you have customer `sources` option - you need to add `{ selector: 'img', attr: 'srcset' },` to arrays of `sources`

Hope it helps

**Comment by graemec23** [comment]
Hey @s0ph1e, thank for you the quick reply. I added that to the sources option, and now I can see the images in the folder. However in the html, the srcset is still pointing to the old folder directory, but i think the src is correct. 

Thanks

**Comment by s0ph1e** [comment]
@graemec23 it would be great if you can provide reproducible example with wrong html - then I can take closer look on issue

**Comment by graemec23** [comment]
Hello @s0ph1e, im using the lazyload on https://github.com/verlok/lazyload, not sure if this will help? 

```
<img
          src="/images/folder1/image.png"
          class="lazyload img-fluid"
          srcset="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVQYV2NgYAAAAAMAAWgmWQ0AAAAASUVORK5CYII="
          data-sizes="auto"
          data-srcset="/images/folder1/image.png"
          alt="Image 2"
        />
```

**Comment by s0ph1e** [comment]
Hi @graemec23 

Looks like in your case it loads images from `data-srcset` attribute and not from `srcset`. I suggest to try with `{ selector: 'img', attr: 'data-srcset' }` in `sources` option - then I believe it will be loaded and updated in result html correctly

**Comment by graemec23** [comment]
Thank you @s0ph1e that worked. Thank you for the prompt feedback :)

On a separate issue, * I dont mind opening a separate ticket, but I have some background images in inline tag at the top of the page, is there anything else I have to specify in the sources?

Thanks again

**Comment by s0ph1e** [comment]
@graemec23 if it uses same library which loads images from `data-srcset` attribute you can use `{ selector: '[data-srcset]', attr: 'data-srcset' },` - it will check all html elements with `data-srcset` attribute. 

Scraper uses cheerio to select html elements so `selector` can be any [selector that cheerio supports](https://github.com/cheeriojs/cheerio#selectors). It follows jquery syntax - so you can experiment with selectors as if you use jquery :)

**Comment by graemec23** [comment]
@s0ph1e Thank you Sophie. I I will take a look, its just a standard background image in

<style>
.element {
background-image: url("/image/icon.svg")
}
</style>

**Comment by s0ph1e** [comment]
@graemec23 ensure that you have `{ selector: 'style' },`  in sources option, then it will be downloaded correctly :)

**Comment by graemec23** [comment]
@s0ph1e I just updated my sources, however the background images aren't showing. Looking at the source, the background url doesnt have any single or double quotes, could that be causing the issue?

background-image: url(/Static/images/icons/ZoomIn-Black.svg);

**Comment by s0ph1e** [comment]
Hi @graemec23 
This should not be a problem, it handles quotes, double quotes and no quotes.

You can try to run it in debug mode [as described here](https://github.com/website-scraper/node-website-scraper/blob/master/README.md#log-and-debug), maybe it will help to understand what went wrong
