### ISSUE TITLE
Feature request: Plug-in's meta-data

### ISSUE THREAD

**Issue by Asaf-S** [website-scraper/node-website-scraper#407]
### Configuration
**version:** website-scraper@4.2.1 

**options:** 
```js
{
  urls: [websiteUrl],
  urlFilter: function (url) {
    return url.indexOf(websiteUrl) === 0;
  },
  recursive: true,
  maxDepth: 100,
  prettifyUrls: true,
  filenameGenerator: 'bySiteStructure',
  directory: './'+directory,
  plugins: [ new MyPlugin() ],
};
```

### Description

Hey, love your project! Writing my own plugin turned out to be an easy and fun experience.
But I found it impossible to pass meta-data (like AWS S3 bucket name) from the options into the plugin's methods (like registerAction('saveResource', async ({resource}) => {}))

**Expected behavior:** 
Being able to add a meta-data key to the options, like this:
```js
const options={
  metaData: {
    bucketName: req.params.bucketName
  }
}
```
And later being able to get it from the plugin's method, like this:
```js
registerAction('saveResource', async ({resource,metaData}) => {}))
```

**Actual behavior:** 
Not possible.

**Comment by s0ph1e** [comment]
Hey @Asaf-S 👋 

Thank you for feedback :) and sorry for late response

Do I understand correctly that you want to save some meta data for each `resource` object? If yes - then please take a look on [afterResponse action](https://github.com/website-scraper/node-website-scraper#afterresponse) - it allows to add metadata to each resource.

**Comment by Asaf-S** [comment]
Not exactly.

I receive the bucket name from the request object, so the only place I can let your library know about it is the options (that's why I suggested adding meta-data to the options).

Also, I need to use the bucket name in the 'saveResource' action of the plugin, but I cannot get information from the request anymore in that action, since the context had changed.

Your suggestion, to add the meta-data to each resource in the 'afterResponse' action, is also too late, as I already lost context and cannot reach the request object.

**Comment by s0ph1e** [comment]
Hi again @Asaf-S 

If you know some data needed by plugin before calling website-scraper - you can pass it to your plugin constructor and then use it for actions, for example:
```javascript
const options = {
  urls: [websiteUrl],
  urlFilter: function (url) {
    return url.indexOf(websiteUrl) === 0;
  },
  recursive: true,
  maxDepth: 100,
  prettifyUrls: true,
  filenameGenerator: 'bySiteStructure',
  directory: './'+directory,
  plugins: [ new MyPlugin({bucketName: req.params.bucketName}) ],
};
```
You can see how it is implemented in [puppeteer plugin](https://github.com/website-scraper/website-scraper-puppeteer#usage)

will this approach work for your case?
