### ISSUE TITLE
Add retries for failed requests

### ISSUE THREAD

**Issue by tverona1** [website-scraper/node-website-scraper#412]
It would be useful to add retries for failed requests.

Something like: https://github.com/FGRibreau/node-request-retry (for a drop-in replacement to request) or https://github.com/sindresorhus/got#retry (if moving to something other than request going forward).

Thanks!

**Comment by s0ph1e** [comment]
Hey @tverona1 

Thank you for suggestion 👍 
I'm not going to do it right now, but this improvement can be implemented during migration from `request` to some other library https://github.com/website-scraper/node-website-scraper/issues/401

**Comment by s0ph1e** [comment]
`request` was replaced with `got` in https://github.com/website-scraper/node-website-scraper/pull/445 and starting from next version v5 it will be possible to use retries by passing got options, e.g. 
```javascript
const options = {
	urls: [ 'http://example.com/' ],
	directory: testDirname,
	request: {
		throwHttpErrors: true,
		retry: {
			limit: 2,
			methods: ['GET'],
			statusCodes: [500]
		}
	}
};
```
