### ISSUE TITLE
URLs with colon (:) fail to save on Windows

### ISSUE THREAD

**Issue by tverona1** [website-scraper/node-website-scraper#413]
URLs that contains colons fails to save on Windows:
website-scraper:info saving resource { url: "http://scp-wiki.wdfiles.com/local--files/nav:side/default.png", filename: "scp-wiki.wdfiles.com\local--files\nav:side\default.png", depth: 1 } to fs +3ms
Unhandled rejection Error: f:\scp\scp-wiki.wdfiles.com\local--files\nav:side contains invalid WIN32 path characters.
    at Object.mkdirs (C:\Users\arcade\Documents\GitHub\node-website-scraper\node_modules\fs-extra\lib\mkdirs\mkdirs.js:18:22)
    at Object.mkdirs (C:\Users\arcade\Documents\GitHub\node-website-scraper\node_modules\universalify\index.js:5:67)
    at C:\Users\arcade\Documents\GitHub\node-website-scraper\node_modules\fs-extra\lib\output\index.js:20:11
    at C:\Users\arcade\Documents\GitHub\node-website-scraper\node_modules\universalify\index.js:23:46

In by-site-structure.js, colons in host are escaped but not in the filePath:
	filePath = path.join(host.replace(':', '_'), filePath);

**Comment by tverona1** [comment]
Also, addressing the above exposes another issue: The normalized relative URL is over-escaped when it contains colon.

Repro: Try downloading the CSS file @ http://scp-wiki.wdfiles.com/local--code/component%3Atheme/1

URLs that contains colons in this file are over-escaped. For example:
     background: url(../../local--files/component**%253A**theme/body_bg.png) top left repeat-x;

**Comment by s0ph1e** [comment]
Hi @tverona1 👋 

Thank you for reporting it, will take closer look on this bug
I didn't know `:` is allowed in path)

**Comment by tverona1** [comment]
FYI, I worked around this by:

```
const bySiteStructureFilenameGenerator = require('website-scraper/lib/filename-generator/by-site-structure');

var illegalRe = /[\?<>:\*\|"]/g;
var controlRe = /[\x00-\x1f\x80-\x9f]/g;  
var windowsReservedRe = /^(con|prn|aux|nul|com[0-9]|lpt[0-9])(\..*)?$/i;
var windowsTrailingRe = /[\. ]+$/;

function sanitize(input, replacement) {
  var sanitized = input
    .replace(illegalRe, replacement)
    .replace(controlRe, replacement)
    .replace(windowsReservedRe, replacement)
    .replace(windowsTrailingRe, replacement);
  return sanitized;
}
...
class MyPlugin {
	apply(registerAction) {
		registerAction('generateFilename', ({resource}) => {
			var fileName = bySiteStructureFilenameGenerator(resource, { defaultFilename: 'index.html' });
			return sanitize(fileName, '_');
		});
...
```

BTW, the plugins are awesome! Very easy to extend the behavior.

**Comment by s0ph1e** [comment]
Hi @tverona1 

Sorry for late response and thank you for sharing your solution 👍 
I'm considering to add this logic into filename generators. Do I understand correctly that all  `illegalRe`, `controlRe `, `windowsReservedRe ` and `windowsTrailingRe ` are not allowed only for windows? Or they are not allowed also on other platforms?

**Comment by tverona1** [comment]
See https://github.com/parshap/node-sanitize-filename/blob/master/index.js
The windowsReservedRe are only for Windows.
