### ISSUE TITLE
Allow changing filename only and keeping the destination path

### ISSUE THREAD

**Issue by maxloh** [website-scraper/node-website-scraper#416]
In the current API design, if we write plugin to change the filename of downloaded files, we would be required to handle the destination path of files too.

It would be better if there is some way to change only the filename. 

Possible way includes:
1. Making the bySiteStructure plugin extendable
2. Separate the API for changing filename and destination path in the generateFilename action.
3. Add a getPath method to the [Resource class](https://github.com/website-scraper/node-website-scraper/blob/master/lib/resource.js).

**Comment by s0ph1e** [comment]
Hi @maxloh 

Thank you for suggestion. 

I'm not sure if it's frequently needed, I'm not going to implement such functionality in nearest future. 
I suggest to create separate configurable plugin for this case based on bySiteStructure filename generator.
