### ISSUE TITLE
Package is hacked?

### ISSUE THREAD

**Issue by gerhardsletten** [website-scraper/node-website-scraper#418]
Just reported a security vulnerability for this package as it insert suspicious content into the page you crawled, so please avoid using it!

A unsupportedbrowser.html link is inserted into the html and this file contains suspicious content

**Comment by aivus** [comment]
Hey @gerhardsletten 

Could you please provide any additional information?

I suppose that unsupportedbrowser.html might be a part of the website you are scrapping. Try another website to verify.

**Comment by gerhardsletten** [comment]
@aivus Sorry, looks like the page I was trying to download was rather old, and that the problem was 3rd party scripts used in it..
