### ISSUE TITLE
Follow meta http-equiv redirects

### ISSUE THREAD

**Issue by MartinMuzatko** [website-scraper/node-website-scraper#428]
### Configuration
**version:** 4.2.3
**options:**
```js
{
        urls: [ 'https://schmalz-connect-suite-docs.netlify.app/' ],
        directory: './tmp',
        maxRecursiveDepth: 20,
        recursive: true,
        filenameGenerator: 'bySiteStructure',
        urlFilter: url => url.startsWith('https://schmalz-connect-suite-docs.netlify.app'),
}

```
### Description

Follow meta `http-equiv` redirects

**Expected behavior:** I want the scraper to be able to also follow the contents of 
``` html
<meta http-equiv="refresh" content="0,url=./de">
```

**Actual behavior:** right now, the scraper stops at the index file and does not continue from there.

**Comment by aivus** [comment]
Hey @MartinMuzatko 👋 

The `website-scraper` module doesn't run or interpretate html/js code. 

Have you tried to use [website-scraper-puppeteer](https://github.com/website-scraper/website-scraper-puppeteer)? It's loading pages using Chrome and executes all scripts and follows all meta tags like a regular browser?

**Comment by MartinMuzatko** [comment]
hello :)

Puppeteer is not possible for us right now, as it is hard to put inside a docker container.
`website-scraper` downloads paths matched by css-like selectors consumed by cheerio. I think
If there would be a possibility to parse the content of a selector, this would be already enough to deal with http-equiv as it would be a regular `anchor` and resume scraping from there.

Which hook would I need to use to create a plugin for that?

Thanks in advance.

**Comment by MartinMuzatko** [comment]
This is okay for me. Thanks for the help! :)

If you want, we can close this issue.

**Comment by s0ph1e** [comment]
Ok, closing issue then
Feel free to open new issues if you have more questions/problems
