### ISSUE TITLE
Feature Request: Downloading multiple video sources

### ISSUE THREAD

**Issue by ChrisOdicho** [website-scraper/node-website-scraper#430]
I was wondering if it would be easy enough to add support for multiple video sources?

For example, given this input:

```html
<video>
    <source src="vid1.webm" />
    <source src="vid2.mp4" />
</video>
```

We should see the following resources:

```
media/vid1.webm
media/vid2.mp4
```

Thanks for the amazing work, this library is awesome!

**Comment by s0ph1e** [comment]
Hi @ChrisOdicho 👋 

I think it should work for multiple video sources now with [current rule in config](https://github.com/website-scraper/node-website-scraper/blob/master/lib/config/defaults.js#L29)  . If it doesn't - then it's a bug. Could you please check it?

**Comment by ChrisOdicho** [comment]
> Hi @ChrisOdicho 👋
> 
> I think it should work for multiple video sources now with [current rule in config](https://github.com/website-scraper/node-website-scraper/blob/master/lib/config/defaults.js#L29) . If it doesn't - then it's a bug. Could you please check it?

Ah it turns out my input HTML didn't actually have multiple sources. I tested with another document that does, and it downloads them correctly.

Thanks @s0ph1e!
