### ISSUE TITLE
Emergency Stop Feature ?

### ISSUE THREAD

**Issue by dobrys** [website-scraper/node-website-scraper#431]
This is not a Issue, 
Just need to know, are there "emergency stop" feature ?
I mean - can I send a command or something - that will abort scraping ?

**Comment by s0ph1e** [comment]
Hi @dobrys 👋
There is no such feature now

**Comment by aivus** [comment]
Just use `kill -9 pid` to kill the process as a last resort.

**Comment by dobrys** [comment]
thanks, for your answer
I'm using website-scraper-puppeteer plugin, can I  send command to "website-scraper-puppeteer" to stop puppeteer (browser) ?
As this happens in "registerAction('afterFinish', () => this.browser && this.browser.close());"

**Comment by s0ph1e** [comment]
Hi @dobrys 
For plugin it's also not possible to send stop command before all resources are downloaded. Could you please explain why do you need to stop it before downloading is finished?
