### ISSUE TITLE
Ignore offsite requests

### ISSUE THREAD

**Issue by karllson** [website-scraper/node-website-scraper#432]
Aloha,

this is not an issue.
Just want to know if there is a way to ignore offsite requests (e.g. eBay refers to a Facebook page, stay on eBay only).

Since plugins are like middlewares, I'm not sure if a request can be canceled from the context of a plugin.

If this is not possible, would you accept a PR for it?

Keep up the good work!

**Comment by s0ph1e** [comment]
Hi @karllson 👋

Sorry for late response and thank you for interest in this module!

Yes, it's possible to ignore some requests, please check [urlFilter option](https://github.com/website-scraper/node-website-scraper#urlfilter)
