### ISSUE TITLE
Issue with // URLs

### ISSUE THREAD

**Issue by ap1969** [website-scraper/node-website-scraper#440]
### Configuration
**version:** [result of `npm ls website-scraper --depth 0` command]
4.2.3 

**options:** [provide your full options object]
```

const options = {
  urls: ['https://4udwl.csb.app/'],
  directory: './output'
};



```

### Description

This page has a couple of links where the URL is defined as //....., meaning it will use either http or https, depending on whether your browser is loading the http or https version of the parent page

**Expected behavior:**
Link should remain unchanged.

**Actual behavior:** [What actually happens]
Link is corrupted:

```
<script src="//codesandbox.io/static/browserfs12/browserfs.min.js" type="text/javascript"></script>
gets turned into 
<script src="js/browserfs.min.js" type="text/javascript"></script>
```

and

```
<link rel="stylesheet" id="bootstrap-css" href="//cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css?ver=5.7.1" type="text/css" media="all" />

gets turned into 

<link rel="stylesheet" id="bootstrap-css" href="css/bootstrap.min.css" type="text/css" media="all">
```

The saved HTML is attached:
[index.zip](https://github.com/website-scraper/node-website-scraper/files/6377070/index.zip)

**Comment by aivus** [comment]
Hi @ap1969 

> Expected behavior:
Link should remain unchanged.

The idea of this module is to download website with it's content and with it's dependencies.

If you want to skip some external dependencies you can use [urlFilter](https://github.com/website-scraper/node-website-scraper#urlfilter) option or [maxDepth](https://github.com/website-scraper/node-website-scraper#maxdepth) option according to your needs

**Comment by ap1969** [comment]
Hi ,
Yeah, I understand that, and I already had a urlfilter in place to download the main domain dependencies only - the same urlfilter provided as an example:

```
 urlFilter: function(url) {
    return url.indexOf('http://example.com') === 0;
  },
```

So the //cdn.... resource should have been ignored and retained as-is, but it wasn't.

Andy

**Comment by s0ph1e** [comment]
Hi @ap1969 

Could you please share your `urlFilter` option so we can check why it's not working?
You can also [enable debug logs](https://github.com/website-scraper/node-website-scraper#log-and-debug) and check if your `urlFilter` works correctly. It should contains logs like `filtering out .... by url filter`
