### ISSUE TITLE
where to find puppeteer

### ISSUE THREAD

**Issue by CodeStudent09** [website-scraper/node-website-scraper#452]
### Configuration
**version:** [result of `npm ls website-scraper --depth 0` command]

**options:** [provide your full options object]
```js



```

### Description
I am trying to find 'puppeteer' in the website scraper puppeteer lib for import into the scraper.js file.
i moved the 'master' folder to my /js directory and renamed it "scraper". then I changed the references to all the referenced classes in each file to reflect my folder move and rename (added '/js/scraper/' to the beginning of all them basically.

now, in debug on chrome, i am getting 
scraper.js:1 Uncaught ReferenceError: require is not defined
and it's pointing to
const puppeteer = require('puppeteer');

any help is appreciated!
### Additional Information

[Any additional information, configuration or data that might be necessary to reproduce the issue]

**Comment by aivus** [comment]
This is a Node.js package and it cannot be used in browser.

All examples of using it can be found in README.md file from this repo or [website-scraper-puppeteer/README.md](https://github.com/website-scraper/website-scraper-puppeteer/blob/master/README.md) (if you want to use puppeteer)
