### ISSUE TITLE
High NPM Vulnerability

### ISSUE THREAD

**Issue by earlvhin** [website-scraper/node-website-scraper#453]
│ High          │ Denial of Service                                            │
├───────────────┼────────────────────────────────────────
│ Package       │ css-what                                                     │
├───────────────┼────────────────────────────────────────
│ Patched in    │ >=5.0.1                                                      │
├───────────────┼────────────────────────────────────────
│ Dependency of │ website-scraper                                              │
├───────────────┼────────────────────────────────────────
│ Path          │ website-scraper > cheerio > css-select > css-what            │
├───────────────┼────────────────────────────────────────

**Comment by s0ph1e** [comment]
Hi @earlvhin 
Thank you for reporting the issue. It's a vulnerability in one of the dependencies https://github.com/cheeriojs/cheerio/issues/1924, let's wait for a fix from cheerio maintainers

**Comment by aivus** [comment]
1. Vulnerability was fixed in `css-what`
2. This security report had wrong version condition because only [v4.0.0 and v5.0.0](https://www.npmjs.com/advisories/1754) of `css-what` were affected, but cheerio(via css-select) used version `2.1`.
