### ISSUE TITLE
Crawling rate limit or requeue?

### ISSUE THREAD

**Issue by abale** [website-scraper/node-website-scraper#485]
Is there a simple way to re-queue a page for crawling?  Many sites employ request rate limiting (429 http status code) and typically it's a question of putting that back in the queue for retry.

An alternative would be a function to rate limit the crawler beyond max concurrency - perhaps a global maximum requests/s (with the ability to provide less-than-1 for slower crawling).

Setting maxConcurrency to 1 still crawls too quickly.

**Comment by s0ph1e** [comment]
Hi @abale 👋 

Sorry for late response.

To achieve retries I suggest to check [request option](https://github.com/website-scraper/node-website-scraper#request). It uses `got` module inside `website-scraper` to make http requests and I suppose it's possible to configure `got` to do retries when request fails.

Also you can try to add delays between requests - please check an example of [beforeRequest action usage](https://github.com/website-scraper/node-website-scraper#beforerequest)

Hope it helps
