### ISSUE TITLE
[not serious] Unsure of how to use urlFilter 

### ISSUE THREAD

**Issue by xsCalamity** [website-scraper/node-website-scraper#487]
Good afternoon. I don't have a bug report or anything of the sort, but I do have a problem -- which is why I'm here -- I've tried everything I could think of.

My problem is with urlFilter. I want it to filter out everything EXCEPT ones that start with a certain string (for example, **https://somebody-has-a.web-site/search?=** <-- Do note this is not a real site.
I'm unsure of how to do that properly, and it ends up either not working at all (only downloading one site without any images, just HTML and CSS) or downloading every website that it links to (privacy policies, terms and conditions, among other things). Any help is appreciated, thank you very much.

--And, for the record, the website's terms and conditions do not state that I _can't_ web scrape off of them, and their website is full of scraped content.

**Comment by xsCalamity** [comment]
Closing the issue quite literally 4 minutes later because I was going about it all wrong. I apologize for the notification(s), and now I'm making myself feel like an idiot, lol.

**Comment by aivus** [comment]
No problem :)
