### ISSUE TITLE
Default non-downloaded paths to alternate url

### ISSUE THREAD

**Issue by ChristopherJohnson25** [website-scraper/node-website-scraper#490]
Hi, can I set this up so only first page is 1 downloaded (default?), but all links on that page should default to baseurl/signup/ (for example).

Another example, 

`<a href="/signup">Sign Up</a>`

Right now this opens /signup, is there an option to open www.originalurl.com/signup ??

**Comment by s0ph1e** [comment]
Hi @ChristopherJohnson25 

Sorry for the late response
It should be possible with [getReference action](https://github.com/website-scraper/node-website-scraper#getreference). You can also check [this test](https://github.com/website-scraper/node-website-scraper/blob/master/test/functional/update-missing-sources/update-missing-sources.test.js) - it looks like it implements something similar to your needs.

Hope it helps

**Comment by ChristopherJohnson25** [comment]
Thanks @s0ph1e  - I will test this.
