### ISSUE TITLE
TypeError: text.replace is not a function

### ISSUE THREAD

**Issue by ChristopherJohnson25** [website-scraper/node-website-scraper#493]
See error below, turning on ignoreErrors then fails to save any .css file. 

node_modules/css-url-parser/lib/css-parser.js:13
        text = text.replace(commentRegexp, '');
                    ^

TypeError: text.replace is not a function

**Comment by s0ph1e** [comment]
Hi @ChristopherJohnson25 

Thanks for reporting a bug, looks like it may be related to yesterday's update https://github.com/website-scraper/node-website-scraper/releases/tag/v5.1.0

I've checked it on my side but I cannot reproduce an error. Do you have a reproducible example?

**Comment by ChristopherJohnson25** [comment]
Hi @s0ph1e  - you can try to scrape Substack URL, here is an example: 

https://sarahwilson.substack.com/p/why-im-back-to-newslettering?s=r

**Comment by s0ph1e** [comment]
Hi @ChristopherJohnson25 

I've deprecated version 5.1.0 because of introduced bugs. Please use 5.0.0 or latest
