### ISSUE TITLE
French characters "à" are not converted correctly 

### ISSUE THREAD

**Issue by Jeremytijal** [website-scraper/node-website-scraper#500]
Hi Sophie,

I noticed that some non-English (French) content end up not getting converted correctly. As a random example, try scraping this page: https://ensemblesurleterrain.bouyguestelecom.fr the result https://test-webscrapper.netlify.app

You'll see that the page is saved with a bunch of � characters in place of the "à"

This problem existed before the last PR. I thought it would be solved, but it was not.

**Comment by s0ph1e** [comment]
Hi @Jeremytijal 👋

Thank you for reporting an issue.
Could you please check if that happens with the latest version 5.2.0? I'll be able to test it by myself later today or tomorrow

**Comment by s0ph1e** [comment]
Yep, now I see it. The fix works when html response contains a charset in the `content-type` header. In this case there is no charset in the header and it saves it in binary as it was in previous versions.

Looks like it makes sense to use utf8 for html files if there was no charset. @phawxby WDYT (as the author of the latest fix)?

**Comment by s0ph1e** [comment]
I like the idea of getting the encoding from html or css content, it sounds better than using utf8 as default and should not be difficult to do.

Most probably I will not have time to implement it in the near future so I really appreciate any help with it.

Thank you for your input and enjoy your vacation without laptop @phawxby 🏖️🌴
