### ISSUE TITLE
Demo is gone

### ISSUE THREAD

**Issue by rainb3rry** [website-scraper/node-website-scraper#505]
Demo is gone, https://scraper.nepochataya.pp.ua/

**Comment by rainb3rry** [comment]
<img width="873" alt="Screen Shot 2022-09-01 at 1 10 43 PM" src="https://user-images.githubusercontent.com/26173028/187844002-5c7fd055-c1f3-4cb6-b524-a1f6a182252f.png">

**Comment by aivus** [comment]
Hello @rainb3rry 

Here is the reason for turning off the demo.
https://github.com/website-scraper/demo/issues/45#issuecomment-1088492073

I'll remove the link from the readme.

_Issue is moved to demo repository_
