### ISSUE TITLE
Design new logo

### ISSUE THREAD

**Issue by s0ph1e** [website-scraper/node-website-scraper#515]
The current logo is quite old, it would be nice to update it on GitHub and in the documentation.

Current logo:
![1(3)](https://user-images.githubusercontent.com/2333969/192491787-a8e1fe88-ce75-466c-8e11-7c15d8379e9e.jpg)

New logo requirements:
* no color preference, but would be nice if it looks good on both white and black backgrounds
* it may contain the first letters of the module's name (W, like now) or somehow highlight the module's purpose (downloading websites) or both

If you would like to contribute to a logo update and need more info - don't hesitate to contact me

**Comment by DeepRahangdale** [comment]
I would like to work on this . You can assign this to me.

**Comment by s0ph1e** [comment]
Hi @DeepRahangdale 👋 

Happy to hear 👍 Feel free to contact me if you need any additional info or just propose a PR with a suggestion
