### ISSUE TITLE
lazy load images are not downloading

### ISSUE THREAD

**Issue by chaybcr** [website-scraper/node-website-scraper#518]
in my site, the images outside the viewport will load once we scroll through the page, in this scenario those images are not downloading to local directory. Kindly help me what can be done to get the images also loaded

**Comment by aivus** [comment]
Hello @chaybcr 

Consider using [website-scraper/website-scraper-puppeteer](https://github.com/website-scraper/website-scraper-puppeteer) for dynamic websites
