### ISSUE TITLE
Incorrect source code for dynamic javascript src

### ISSUE THREAD

**Issue by diegomachado1** [website-scraper/node-website-scraper#530]
### Configuration
**version:** website-scraper@5.3.1

**options:** 
```js

const options = {
  urls: ["https://ultrak9pro.com/"],
  directory: "./tmp/",
  sources: [
    {selector: 'script', attr: 'src'}
  ]
};

```

### Description

It consider dynamic javascript src like common html pages and add `<html><head><body>` tags in the file source code.
Take a look at `<script src="https://ultrak9pro.com/statics/js/statics_js.php?static=https://ultrak9pro.com"></script>`

This file will not be considered a js file and for some reason the scraper will ad html tags in it.

**Expected behavior:** The file should be considered a JS file since it's in `<script src="...`

**Actual behavior:** The file is scraped like an html file. And the scraper adds html code inside its source code

**Comment by ninja1879** [comment]
i can do it

**Comment by ninja1879** [comment]
If you want the scraper to treat this file as a JavaScript file and not modify its source code, you need to modify the configuration of the scraper.

**Comment by aivus** [comment]
Hello @diegomachado1 

Looks like the reason of this behaviour is wrong `content-type` header sent by website.

If you open `https://ultrak9pro.com/statics/js/statics_js.php?static=https://ultrak9pro.com` and check response headers you will see `Content-Type: text/html` there

**Comment by aivus** [comment]
@diegomachado1 you can override the header for this request by using custom plugin with [afterResponse](https://github.com/website-scraper/node-website-scraper#afterresponse) action.
